CXX=g++
CPPFLAGS=-g -fpermissive -I/usr/include/libusb-1.0 -I../../libpixyusb2/include -I../../arduino/libraries/Pixy2
LDLIBS=../../../../build/libpixyusb2/libpixy2.a -lusb-1.0 -lcurl -lpthread

SRCS=capture-json-cam.cpp

OBJS=$(subst .cpp,.o,$(SRCS))

all: capture-json-cam 

clean:
	rm -f *.o capture-json-cam 

get_blocks: $(OBJS)
	$(CXX) $(LDFLAGS) -o capture-json-cam $(OBJS) $(LDLIBS)
